// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/raphi011/kb/internal/index"
	"github.com/raphi011/kb/internal/markdown"
)

// LayoutParams holds all data needed for a full page render.
type LayoutParams struct {
	Title          string
	ManifestJSON   string
	Tree           []*FileNode
	Tags           []index.Tag
	FlashcardNotes []index.NoteFlashcardCount
	Bookmarks      []BookmarkEntry
	ContentCol     templ.Component
	Headings       []markdown.Heading
	OutgoingLinks  []index.Link
	Backlinks      []index.Link
	CalendarYear   int
	CalendarMonth  int
	ActiveDays     map[int]bool
	FlashcardPanel *FlashcardPanelData // nil = don't show
	SlidePanel     *SlidePanelData
	NotePath       string
}

// FileNode represents a file or directory in the sidebar tree.
type FileNode struct {
	Name     string
	Path     string
	IsDir    bool
	IsActive bool
	IsOpen   bool
	Children []*FileNode
}

// BreadcrumbSegment represents one segment of a breadcrumb path.
type BreadcrumbSegment struct {
	Name       string
	FolderPath string
}

// FolderEntry represents a file or subdirectory in a folder listing.
type FolderEntry struct {
	Name  string `json:"name"`
	Path  string `json:"path"`
	Title string `json:"title,omitempty"`
	IsDir bool   `json:"isDir"`
}

func Layout(p LayoutParams) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if p.Title != "" {
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(p.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/server/views/layout.templ`, Line: 60, Col: 13}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " — kb")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "kb")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</title><link rel=\"stylesheet\" href=\"/static/style.min.css\"><link rel=\"stylesheet\" href=\"/static/chroma.css\"><script>\n\t\t\t(function(){var d=document.documentElement,s=d.style;var u;try{u=JSON.parse(localStorage.getItem('zk-ui'))||{}}catch(e){u={}}d.setAttribute('data-theme',u.theme||(window.matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'));if(u.sidebarWidth)s.setProperty('--sidebar-width',u.sidebarWidth+'px');if(u.tocPanelWidth)s.setProperty('--toc-width',u.tocPanelWidth+'px');if(u.zen)d.classList.add('zen')})();\n\t\t</script></head><body hx-indicator=\"#nav-loader\"><div id=\"nav-loader\" class=\"nav-loader\"></div><div id=\"progress-bar\"></div><header id=\"topbar\"><button id=\"mob-menu-btn\" class=\"btn btn-icon\" aria-label=\"Menu\">&#9776;</button> <a id=\"logo\" href=\"/\" hx-get=\"/\" hx-target=\"#content-col\" hx-swap=\"innerHTML transition:true\" hx-push-url=\"true\"><span class=\"logo-dot\"></span><strong>kb</strong></a><div id=\"topbar-spacer\"></div><button id=\"cmd-trigger\" type=\"button\"><span>Search</span><kbd>&#8984;K</kbd></button> <button id=\"zen-toggle\" class=\"btn btn-icon\" type=\"button\" aria-label=\"Toggle zen mode\" title=\"Toggle zen mode\">&#8865;</button> <button id=\"theme-toggle\" class=\"btn btn-icon\" type=\"button\" aria-label=\"Toggle theme\"><span id=\"theme-icon\">&#9790;</span></button></header><div id=\"sidebar-backdrop\"></div><div id=\"layout\"><nav id=\"sidebar\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Sidebar(p.Tree, p.Tags, p.FlashcardNotes, p.Bookmarks).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<a class=\"sidebar-footer\" href=\"/settings\" hx-get=\"/settings\" hx-target=\"#content-col\" hx-swap=\"innerHTML transition:true\" hx-push-url=\"true\" title=\"Settings\"><span class=\"sidebar-footer-icon\">&#9881;</span> Settings</a></nav><div class=\"resize-handle\" id=\"sidebar-resize\"></div><div id=\"main\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = p.ContentCol.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"resize-handle\" id=\"toc-resize\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TOCPanel(p.Headings, p.OutgoingLinks, p.Backlinks, false, p.CalendarYear, p.CalendarMonth, p.ActiveDays, p.FlashcardPanel, p.SlidePanel, p.NotePath).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div><dialog id=\"cmd-dialog\"><div id=\"cmd-box\"><div id=\"cmd-input-row\"><span class=\"cmd-icon-search\">&#8984;</span> <input id=\"cmd-input\" type=\"text\" placeholder=\"Search...\" autocomplete=\"off\"></div><div id=\"cmd-results\" class=\"scrollable\"></div><div id=\"cmd-footer\"><span class=\"cmd-hint\"><kbd>&#8593;&#8595;</kbd> navigate</span> <span class=\"cmd-hint\"><kbd>&#8629;</kbd> open</span> <span class=\"cmd-hint\"><kbd>esc</kbd> close</span></div></div></dialog> <dialog id=\"media-dialog\"><div id=\"media-container\"></div></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("<script>window.__ZK_MANIFEST = "+p.ManifestJSON+";</script>").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<script src=\"/static/htmx.min.js\"></script><script src=\"/static/app.min.js\"></script><script src=\"/static/mermaid.min.js\"></script><script>\n\t\t\tif(window.mermaid){mermaid.initialize({startOnLoad:false,theme:'dark'});mermaid.run({nodes:document.querySelectorAll('.mermaid')});}\n\t\t</script><div id=\"toast-container\"></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
